//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskMe.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Header { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> EditUser { get; set; }
        public Nullable<System.DateTime> AnswerDate { get; set; }
        public Nullable<int> AnswerUser { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
